version = 0.10.0
group = io.github.qishr
title = Cascara Schema
description = JSON Schema compatible schema validator, resolver, generator, compiler, decompiler, and store.
url = https://qishr.github.io/cascara/schema/
scm_url = https://github.com/qishr/cascara-schema
scm_conn = scm:git:https://github.com/qishr/cascara-schema.git
scm_dev_conn = scm:git:https://github.com/qishr/cascara-schema.git

cascara_version = 0.10.5
org.gradle.configuration-cache = false