plugins {
    id "io.github.qishr.cascara-meta.java-library" version "0.1.0"
}


repositories {
	mavenLocal()
	mavenCentral()
}


tasks.withType(JavaCompile).configureEach {
    options.release = 21
}


dependencies {
    implementation(platform("io.github.qishr:cascara-meta-bom:$cascara_version"))
    implementation("org.junit.jupiter:junit-jupiter-api")
    implementation("org.junit.jupiter:junit-jupiter-engine")
    implementation('org.junit.platform:junit-platform-launcher')
    implementation('org.mockito:mockito-core')
    implementation('org.mockito:mockito-junit-jupiter')
    implementation('io.github.qishr:cascara-test-common-junit')

    implementation "org.apache.logging.log4j:log4j-api:2.25.5"
    implementation 'org.apache.logging.log4j:log4j-core:2.25.5'
    implementation('io.github.qishr:cascara-logging-log4j')

    implementation('io.github.qishr:cascara-common')
    implementation('io.github.qishr:cascara-common-io')
    implementation('io.github.qishr:cascara-lang-json')
    implementation('io.github.qishr:cascara-logging-log4j')

    implementation(project(':cascara-schema'))
}


tasks.withType(Javadoc).configureEach {
    options.addStringOption('Xdoclint:-missing', '-quiet')
}


test {
    useJUnitPlatform()
    jvmArgs = [
        '--module-path', "$buildDir/modulepath",
        '--add-modules', 'ALL-MODULE-PATH'
    ]
}
